stages:
        - build

build-linux:
        stage: build
        tags:
                - docker
        image: docker.dolphinics.no/sw/docker/ubuntu_mxs_kernel_crosscompile:latest
        artifacts:
                name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
                expire_in: 1 week
                paths:
                        - "mxs-install.tar.gz"
        script:
                - /bin/bash build.sh
